### ISSUE TITLE
Retorno ao top

### ISSUE THREAD

**Issue by edysegura** [lucianoctrl8/proj_ecommerce#8]
Toda vez que colocamos um item no carrinho o usuário é retornado para o topo!

![image](https://cloud.githubusercontent.com/assets/5324414/9027140/9b806364-391f-11e5-8d5c-b3f2fd0cc56f.png)

**Comment by lucianoctrl8** [comment]
Sim. Eu planejei este fluxo de eventos para ocorrer desta forma mesmo, visto que logo após clicar sobre adicionar ao carrinho, uma mensagem é exibida confirmando a açao e em seguida abro a pagina index do projeto novamente. Para que o usuario consulte os itens do carrinho basta clicar em 'Meu Carrinho'. Obrigado.
